package config

const defaultCfgBody = `
{
   "tabloItems":[
      {
         "id":11,
         "name":"ВПП-1",
         "boardID":0,
         "pinID":0,
         "manageBoardID":0,
         "managePinID":1,
         "isActive":true,
         "isInverse":false
      },
      {
         "id":12,
         "name":"ВПП-2",
         "boardID":0,
         "pinID":2,
         "manageBoardID":0,
         "managePinID":3,
         "isActive":false,
         "isInverse":false
      }
   ],
   "objects":[
      {
         "objectID":13,
         "objectName":"DME<p>",
         "panelID":1
      },
      {
         "objectID":14,
         "objectName":"РАЗ ДВА",
         "panelID":1
      },
      {
         "objectID":15,
         "objectName":"KLM",
         "panelID":2
      },
      {
         "objectID":16,
         "objectName":"КПД",
         "panelID":3
      },
      {
         "objectID":17,
         "objectName":"ПДД",
         "panelID":3
      },
      {
         "objectID":50,
         "objectName":"MCP",
         "panelID":3
      },
      {
         "objectID":51,
         "objectName":"ГРМ",
         "panelID":2
      }
   ],
   "items":[
      {
         "id":18,
         "name":"Фид 1",
         "typeID":1,
         "objectID":14,
         "boardID":1,
         "pinID":0,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":5
      },
      {
         "id":19,
         "name":"Фид 2",
         "typeID":1,
         "objectID":14,
         "boardID":1,
         "pinID":1,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":1
      },
      {
         "id":20,
         "name":"Фид 1",
         "typeID":1,
         "objectID":16,
         "boardID":1,
         "pinID":2,
         "isInput":true,
         "isActive":true,
         "isInverse":true,
         "duration":1
      },
      {
         "id":22,
         "name":"ОЛП",
         "typeID":1,
         "objectID":16,
         "boardID":1,
         "pinID":4,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":2
      },
      {
         "id":23,
         "name":"Выкл ДГ",
         "typeID":3,
         "objectID":16,
         "boardID":0,
         "pinID":8,
         "isInput":false,
         "isActive":true,
         "isInverse":false,
         "duration":4
      },
      {
         "id":24,
         "name":"Фид 1",
         "typeID":1,
         "objectID":13,
         "boardID":1,
         "pinID":5,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":1
      },
      {
         "id":25,
         "name":"<hr> Вкл/Выкл",
         "typeID":3,
         "objectID":13,
         "boardID":0,
         "pinID":9,
         "isInput":false,
         "isActive":true,
         "isInverse":false,
         "duration":1
      },
      {
         "id":26,
         "name":"Фид test",
         "typeID":1,
         "objectID":17,
         "boardID":1,
         "pinID":3,
         "isInput":true,
         "isActive":true,
         "isInverse":true,
         "duration":1
      },
      {
         "id":27,
         "name":"Авария мать его!",
         "typeID":2,
         "objectID":17,
         "boardID":1,
         "pinID":7,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":0.5
      },
      {
         "id":28,
         "name":"<hr> Вкл/Выкл ДГ",
         "typeID":3,
         "objectID":17,
         "boardID":0,
         "pinID":10,
         "isInput":false,
         "isActive":true,
         "isInverse":false,
         "duration":1
      },
      {
         "id":29,
         "name":"<hr> Включи меня",
         "typeID":3,
         "objectID":17,
         "boardID":0,
         "pinID":11,
         "isInput":false,
         "isActive":true,
         "isInverse":false,
         "duration":6
      },
      {
         "id":21,
         "name":"УВД <br> >30°",
         "typeID":2,
         "objectID":15,
         "boardID":1,
         "pinID":6,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":2
      },
      {
         "id":53,
         "name":"Фид 5 ",
         "typeID":1,
         "objectID":51,
         "boardID":5,
         "pinID":8,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":1
      },
      {
         "id":54,
         "name":"Test MCP",
         "typeID":1,
         "objectID":50,
         "boardID":1,
         "pinID":10,
         "isInput":true,
         "isActive":true,
         "isInverse":false,
         "duration":2.5
      }
   ],
   "comment":"1. Нужно хорошо все протестировать!\nЖелательно все кейсы которые возможны, их воспроизвести, и проверить правильно ли все отработало.\n\n\n2. Для переноса текста на новую строку в названии, необходимо использовать тэг <br>\nНапример: УВД <br> >30°\n\n\n3.Если нужно вставить пустую строку в название\nнеобходимо использовать тэг <p>\nНапример: DME <p> тогда заголовок объекта станет\nвысотой как у двух строчного.\n\n\n4.Если нужен разделитель для переключателя то в название нужно добавить тэг <hr> \nНапример: <hr> Вкл/Выкл\n\n"
}`
